events/urls.py
from django.urls import path, include
from django.views.decorators.http import require_POST

from . import views


app_name = 'events'


urlpatterns = [
    path('list/', views.EventListView.as_view(), name='event_list'),
    path('detail/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
    path('create/', views.EventCreateView.as_view(), name='event_create'),
    path('update/<int:pk>/', views.EventUpdateView.as_view(), name='event_update'),
    path('delete/<int:pk>/', views.EventDeleteView.as_view(), name='event_delete'),
    path('enroll/', require_POST(views.EventEnrollView.as_view()), name='event_enroll'),
]

realworlddjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/', include('events.urls')),
    path('api/events/', include('events.urls_api')),
]

events/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=90, blank=True, default='', verbose_name='Категория')

    def display_event_count(self):
        return len(self.events.all())
    display_event_count.short_description = 'Количество событий'


    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.title


class Feature(models.Model):
    title = models.CharField(max_length=90, blank=True, default='', verbose_name='Свойство события')

    class Meta:
        verbose_name = 'Свойство'
        verbose_name_plural = 'Свойства'

    def __str__(self):
        return self.title


class Event(models.Model):

    FULLNESS_FREE = '1'
    FULLNESS_MIDDLE = '2'
    FULLNESS_FULL = '3'
    FULLNESS_LEGEND_FREE = '<= 50%'
    FULLNESS_LEGEND_MIDDLE = '> 50%'
    FULLNESS_LEGEND_FULL = 'sold-out'
    FULLNESS_VARIANTS = (
        (FULLNESS_FREE, FULLNESS_LEGEND_FREE),
        (FULLNESS_MIDDLE, FULLNESS_LEGEND_MIDDLE),
        (FULLNESS_FULL, FULLNESS_LEGEND_FULL),
    )

    title = models.CharField(max_length=200, blank=True, default='', verbose_name='Название')
    description = models.TextField(blank=True, default='', verbose_name='Описание')
    date_start = models.DateTimeField(verbose_name='Дата начала')
    participants_number = models.PositiveSmallIntegerField(verbose_name='Количество участников')
    is_private = models.BooleanField(default=False, verbose_name='Частное')
    category = models.ForeignKey(Category,null=True,on_delete=models.CASCADE,related_name='events')
    features = models.ManyToManyField(Feature)
    logo = models.ImageField( blank=True, null=True)


    def display_enroll_count(self):
        return len(self.enrolls.all())

    display_enroll_count.short_description = 'Количество записей'


    def get_enroll_count(self):
        return self.enrolls.count()

    def get_places_left(self):
        return int(self.participants_number or 0) - self.get_enroll_count()

    def get_fullness_legend(self, **kwargs):
        legend = ''
        if int(self.participants_number or 0) > 0:
            legend = Event.FULLNESS_LEGEND_FREE
            places_left = kwargs.get('places_left', None)
            if places_left is None:
                places_left = self.get_places_left()
            if places_left == 0:
                legend = Event.FULLNESS_LEGEND_FULL
            elif places_left < self.participants_number / 2:
                legend = Event.FULLNESS_LEGEND_MIDDLE
        return legend

    def display_places_left(self):
        places_left = self.get_places_left()
        return f'{places_left} ({self.get_fullness_legend(places_left=places_left)})'

    display_places_left.short_description = 'Осталось мест'

    class Meta:
        verbose_name = 'Событие'
        verbose_name_plural = 'События'
        ordering = ['date_start']

    def __str__(self):
        return self.title

    @property
    def rate(self):
        reviews = self.reviews.all()
        sum,count = 0,0
        for rev in reviews:
            sum += rev.rate
            count += 1
        try:
            return round(sum/count,1)
        except:
            return 0


    @property
    def logo_url(self):
        return self.logo.url if self.logo else f'{settings.STATIC_URL}images/svg-icon/event.svg'

    def get_absolute_url(self):
        return reverse('events:event_detail', args=[str(self.pk)])

    def get_update_url(self):
        return reverse('events:event_update', args=[str(self.pk)])

    def get_delete_url(self):
        return reverse('events:event_delete', args=[str(self.pk)])




class Enroll(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete = models.CASCADE,related_name='enrolls')
    event = models.ForeignKey(Event, blank=True, on_delete = models.CASCADE,related_name='enrolls')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.event

class Review(models.Model):
    user = models.ForeignKey(User, blank=True, on_delete = models.CASCADE,related_name='reviews')
    event = models.ForeignKey(Event, blank=True, on_delete = models.CASCADE,related_name='reviews')
    created = models.DateTimeField(auto_now_add=True)
    rate = models.PositiveSmallIntegerField()
    updated = models.DateTimeField(auto_now=True)
    text = models.TextField(blank=True, default='', verbose_name='текст отзыва')

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

events/forms.py
from django import forms
from events.models import Event, Enroll, Category, Feature
# from utils.forms import update_fields_widget

class EventEnrollForm(forms.ModelForm):
    class Meta:
        model = Enroll
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget = forms.HiddenInput()

    def clean(self):
        cleaned_data = super().clean()

        if Enroll.objects.filter(user=cleaned_data['user'], event=cleaned_data['event']).exists():
            raise forms.ValidationError(f'Вы уже записаны на это событие!')

        return cleaned_data


class EventCreateUpdateForm(forms.ModelForm):
    date_start = forms.DateTimeField(label='Дата начала',
                                     widget=forms.DateTimeInput(format="%Y-%m-%dT%H:%M",
                                                                attrs={'type': 'datetime-local'})
                                     )

    class Meta:
        model = Event
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        update_fields_widget(self, ('title', 'description', 'date_start', 'logo',), 'form-control')
        self.fields['is_private'].widget.attrs.update({'class': 'form-check-label'})
        update_fields_widget(self, ('participants_number', 'category', 'features',), 'form-select')

    def clean(self):
        cleaned_data = super().clean()
        participants_number = cleaned_data.get('participants_number')
        if participants_number and participants_number < 5:
            raise forms.ValidationError('Количество участников должно быть от 5')
        return cleaned_data


class EventFilterForm(forms.Form):
    category = forms.ModelChoiceField(label='Категория', queryset=Category.objects.all(), required=False)
    features = forms.ModelMultipleChoiceField(label='Свойства', queryset=Feature.objects.all(), required=False)
    date_start = forms.DateTimeField(label='Дата начала',
                                     widget=forms.DateInput(format="%Y-%m-%d", attrs={'type': 'date'}), required=False)
    date_end = forms.DateTimeField(label='Дата окончания',
                                   widget=forms.DateInput(format="%Y-%m-%d", attrs={'type': 'date'}), required=False)
    is_private = forms.BooleanField(label='Приватное', required=False)
    is_available = forms.BooleanField(label='Есть места', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs.update({'class': 'form-select'})
        self.fields['features'].widget.attrs.update({'class': 'form-select', 'multiple': True})
        # update_fields_widget(self, ('date_start', 'date_end',), 'form-control')
        # update_fields_widget(self, ('is_private', 'is_available',), 'form-check-input')

events/views.py
import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponseForbidden, HttpResponseRedirect

from .forms import EventEnrollForm, EventFilterForm, EventCreateUpdateForm
from .models import *


class EventListView(ListView):
    model = Event
    template_name = 'events/event_list.html'
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_objects'] = Category.objects.all()
        context['feature_objects'] = Feature.objects.all()
        context['filter_form'] = EventFilterForm(self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.prefetch_related('enrolls', 'features', 'reviews').annotate(enroll_count=Count('enrolls'))
        form = EventFilterForm(self.request.GET)
        if form.is_valid():
            category = form.cleaned_data['category']
            features = form.cleaned_data['features']
            date_start = form.cleaned_data['date_start']
            date_end = form.cleaned_data['date_end']
            is_private = form.cleaned_data['is_private']
            is_available = form.cleaned_data['is_available']
            if category:
                queryset = queryset.filter(category=category)
            if features:
                for feature in features:
                    queryset = queryset.filter(features__in=[feature])
            if date_start:
                queryset = queryset.filter(Q(date_start=date_start) | Q(date_start__gt=date_start))
            if date_end:
                queryset = queryset.filter(Q(date_start__lt=date_end) | Q(date_start=date_end))
            if is_private:
                queryset = queryset.filter(is_private=is_private)
            if is_available:
                queryset = queryset.filter(enroll_count__lt=F('participants_number'))
        return queryset.order_by('-pk')

class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        default_object = super().get_object(queryset)
        return default_object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['enroll_form'] = EventEnrollForm(initial={'user': self.request.user, 'event': self.object})
        return context

    def get_template_names(self):
        default_template_names = super().get_template_names()
        return default_template_names


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    template_name = 'events/event_update.html'
    form_class = EventCreateUpdateForm
    success_url = reverse_lazy('events:event_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['is_auth'] = self.request.user.is_authenticated
        return context

    def form_valid(self, form):
        messages.success(self.request, 'Новое событие успешно создано.')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors())
        return super().form_invalid(form)


class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Event
    form_class = EventCreateUpdateForm
    template_name = 'events/event_update.html'

    def get_success_url(self):
        return self.object.get_absolute_url()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        enrolls = self.object.enrolls.select_related('user').all()
        reviews = self.object.reviews.select_related('user').all()
        context['reviews'] = reviews
        dict_rev = dict_data(reviews, 'user_id')
        partps = []
        for enr in enrolls:
            user = enr.user
            rate = dict_rev.get(user.id, 0)
            partps.append({'name': user.get_full_name(), 'email': user.email, 'rate': rate})
        context['partps'] = prepare_data(enrolls, dict_rev, 'user', 0, 'user')
        return context

    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors())
        return super().form_invalid(form)


class EventDeleteView(LoginRequiredMixin, DeleteView):
    model = Event
    template_name = 'events/event_update.html'
    success_url = reverse_lazy('events:event_list')

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        messages.success(request, f'Событие {self.object} удалено.')
        return result

@require_POST
def create_review(request):
    data = {
        'ok': True,
        'msg': '',
        'rate': request.POST.get('rate'),
        'text': request.POST.get('text'),
        'created': datetime.date.today().strftime('%d.%m.%Y'),
        'user_name': ''
    }

    pk = request.POST.get('event_id', '')
    if not pk:
        data['msg'] = 'Событие не найдено'
        data['ok'] = False
        return JsonResponse(data)

    else:
        event = Event.objects.get(pk=pk)

        if not request.user.is_authenticated:
            data['msg'] = 'Отзывы могут отправлять только зарегистрированные пользователи'
            data['ok'] = False
            return JsonResponse(data)

        data['user_name'] = request.user.__str__()

        if Review.objects.filter(user=request.user, event=event).exists():
            data['msg'] = 'Вы уже отправляли отзыв к этому событию'
            data['ok'] = False

        elif data['text'] == '' or data['rate'] == '':
            data['msg'] = 'Оценка и текст отзыва - обязательные поля'
            data['ok'] = False

        else:
            new_review = Review(
                user=request.user,
                event=event,
                rate=data['rate'],
                text=data['text'],
                created=data['created'],
                updated=data['created']
            )

            new_review.save()

        return JsonResponse(data)


class EventEnrollView(LoginRequiredMixin, CreateView):
    model = Enroll
    form_class = EventEnrollForm

    def get_success_url(self):
        return self.object.event.get_absolute_url()

    def form_invalid(self, form):
        messages.error(self.request, form.non_field_errors())
        event = form.cleaned_data.get('event', None)
        if not event:
            event = get_object_or_404(Event, pk=form.data.get('event'))
        redirect_url = event.get_absolute_url() if event else reverse_lazy('events:event_list')
        return HttpResponseRedirect(redirect_url)

    def form_valid(self, form):
        messages.success(self.request, f'Вы записаны на {form.cleaned_data["event"]} ')
        return super().form_valid(form)

events/templates/events/event_list.html
{% extends '__base.html' %}

{% block title %}Список событий{% endblock %}

{% block content %}
    <!-- Start CONTAINER_BAR -->
        <div class="container-fluid mt-3">
            <div class="row mb-4">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-body">
                            <form>
                                <div class="row row-cols-lg-auto g-3 align-items-start">
                                    <div class="col-12">
                                        <label for="category" class="form-label">Категория:</label>
                                        <select class="form-select" id="category">
                                            <option selected="">....................</option>
                                            {% for categorty in category_objects %}
                                                <option value="{{ forloop }}">{{ categorty }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-12">
                                        <label for="features" class="form-label">Свойства:</label>
                                        <select class="form-select" multiple="" id="features">
                                            {% for feature in feature_objects %}
                                                <option value="{{ forloop }}">{{ feature }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                    <div class="col-12 d-md-flex">
                                        <div class="mx-1">
                                            <label for="id_date_start" class="form-label">Дата начала</label>
                                            <input type="date" class="form-control" id="id_date_start">
                                        </div>
                                        <div class="mx-1">
                                            <label for="id_date_end" class="form-label">Дата окончания</label>
                                            <input type="date" class="form-control" id="id_date_end">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-3">
                                    <div class="col-12 d-md-flex">
                                        <div class="form-check me-3">
                                            <input class="form-check-input" type="checkbox" value="" id="is_private">
                                            <label class="form-check-label" for="is_private">
                                                Private
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="is_available">
                                            <label class="form-check-label" for="is_available">
                                                Есть места
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-3">
                                        <button type="submit" class="btn btn-primary">Фильтровать</button>
                                        <button type="submit" class="btn btn-outline-danger">Сбросить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#" data-test="p_start">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_previous">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_1">1</a></li>
                <li class="page-item active"><a class="page-link" href="#" data-test="p_2">2</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_3">3</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_next">Next</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_end">&raquo;</a></li>
            </ul>

            <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-4">
                {% for event in event_objects %}
                <div class="col">
                    <div class="card h-100">
                        <div class="card-header">
                            <h5 class="card-title mb-0">{{ event.title }}</h5>
                            <span data-test="is_private" class="badge bg-dark">{% if event.is_private %}Private{% endif %}</span>
                        </div>
                        <div class="card-body">
                            <h3>{{ event.display_enroll_count }} из {{ event.participants_number }}</h3>
                            <p>участников</p>
                            <ul class="py-2">
                                {%  for feature in event.features.get_queryset %}
                                <li>{{ feature }}</li>
                                {% endfor %}
                            </ul>
                            <p>
                                дата: <strong data-test="date_start">{{ event.date_start|date:"d.m.Y в H:i" }}</strong>
                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="{{ event.get_absolute_url }}" class="btn btn-success">Смотреть</a>
                            <a href="event_update2.html" class="btn btn-outline-primary" title="Изменить">
                                <i class="bi bi-pencil-square"></i>Изменить
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <!-- End CONTAINER_BAR -->
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>